import Link from "next/link";

export default function ContentEn() {
  return (
    <>
      <h1 className="text-2xl sm:text-3xl font-bold mb-6">AI</h1>
      <div className="space-y-6 text-sm text-text-secondary leading-relaxed">
        <p>
          Feedim AI is an artificial intelligence-powered system designed to enhance the safety and quality of content on the platform.
          AI is used in many areas, from content moderation to SEO generation, copyright scanning to profile score calculation.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI-Generated Content</h2>
        <p>
          Feedim requires transparent disclosure of content created with artificial intelligence (text, images, video).
          When creating content, you can declare that your content was generated by AI by enabling the &ldquo;AI content&rdquo; option.
        </p>

        <div className="bg-bg-secondary rounded-[15px] p-4 space-y-3">
          <h3 className="text-sm font-bold text-text-primary">Why do we differentiate?</h3>
          <ul className="list-disc pl-5 space-y-2 text-text-muted text-xs">
            <li><strong className="text-text-primary">Transparency</strong> &mdash; Users have the right to know whether content was created by a human or AI</li>
            <li><strong className="text-text-primary">Trust</strong> &mdash; Distinguishing original human-created content from AI content increases platform trust</li>
            <li><strong className="text-text-primary">Fair discovery</strong> &mdash; Content recommendation algorithms evaluate AI content separately from original content for a fair discovery experience</li>
            <li><strong className="text-text-primary">Legal compliance</strong> &mdash; Many countries are making it a legal requirement to label AI-generated content</li>
          </ul>
        </div>

        <div className="bg-bg-secondary rounded-[15px] p-4 space-y-3 mt-4">
          <h3 className="text-sm font-bold text-text-primary">What happens if not declared?</h3>
          <ul className="list-disc pl-5 space-y-2 text-text-muted text-xs">
            <li>Feedim AI can automatically detect AI generation patterns in text and images</li>
            <li>Content detected as AI-generated but not declared will <strong className="text-text-primary">lower your profile trust score</strong></li>
            <li>In repeated cases, content may be sent to moderation and account restrictions may apply</li>
            <li>Copyright protection cannot be claimed for AI-generated content</li>
          </ul>
        </div>

        <p className="text-xs text-text-muted italic">
          Note: Users who use AI tools as assistants (e.g., spell checking, language correction) but create the core content themselves
          do not need to enable this option. This option is for content that is largely or entirely generated by AI.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI Text Analysis</h2>
        <p>
          Every post, moment, or comment is automatically scanned by AI when published.
          The system analyzes content across various categories and detects content that violates community guidelines.
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Hate speech</strong> &mdash; Expressions containing hatred based on race, religion, gender, or ethnicity</li>
          <li><strong>Profanity and insults</strong> &mdash; Language containing slang, profanity, and personal attacks</li>
          <li><strong>Sexual content</strong> &mdash; Adult-oriented or obscene expressions</li>
          <li><strong>Spam</strong> &mdash; Repetitive, meaningless, or promotional content</li>
          <li><strong>Misinformation</strong> &mdash; Deliberately false or disinformation-type content</li>
        </ul>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI Image Analysis</h2>
        <p>
          Images attached to posts are automatically scanned by AI before publication.
          Image analysis detects inappropriate content in the following categories:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Sexual content</strong> &mdash; Obscene or adult-oriented images</li>
          <li><strong>Violence</strong> &mdash; Images containing blood, injury, or physical violence</li>
          <li><strong>Inappropriate imagery</strong> &mdash; Other visual content that violates community guidelines</li>
        </ul>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI SEO Generation</h2>
        <p>
          Feedim AI automatically generates SEO metadata for every published post. This helps your content
          rank better in search engines and reach more people.
        </p>
        <div className="bg-bg-secondary rounded-[15px] p-4 space-y-3">
          <div className="flex items-start gap-3">
            <span className="text-accent-main font-bold text-xs mt-0.5 shrink-0">Title</span>
            <p className="text-text-muted text-xs">An SEO title suited to your content is automatically generated by AI</p>
          </div>
          <div className="flex items-start gap-3">
            <span className="text-accent-main font-bold text-xs mt-0.5 shrink-0">Description</span>
            <p className="text-text-muted text-xs">Meta description is generated by AI by summarizing your content</p>
          </div>
          <div className="flex items-start gap-3">
            <span className="text-accent-main font-bold text-xs mt-0.5 shrink-0">Keywords</span>
            <p className="text-text-muted text-xs">Keywords suited to the content are determined by AI</p>
          </div>
        </div>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI Copyright Scanning</h2>
        <p>
          Feedim AI performs text, image, and video similarity scanning on content with copyright protection enabled.
          When duplicate content is detected, the content may be placed under moderation. For details, see the{" "}
          <Link href="/help/copyright" className="text-accent-main hover:opacity-80 font-semibold">Copyright Protection</Link> page.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI Profile Score Calculation</h2>
        <p>
          Each user&apos;s trust score is automatically calculated by AI. The profile score is determined by many factors
          including content quality, community interaction, account age, and moderation history.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI Onboarding Check</h2>
        <p>
          When new users register, their chosen username and bio are checked by AI.
          When inappropriate, profanity-containing, or misleading usernames and bios are detected, the account is placed under moderation.
          This ensures the platform provides a safe environment from the very beginning.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">Fail-Open Design</h2>
        <div className="bg-bg-secondary rounded-[15px] p-4">
          <p>
            Feedim AI operates on the <strong className="text-text-primary">fail-open</strong> principle. This means that if any
            technical error or delay occurs in the AI system, content will not be blocked. User experience is always
            the priority; an issue in the AI will not disrupt the content publishing process.
          </p>
        </div>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">AI and Human Moderation</h2>
        <p>
          Feedim AI does not replace human moderation; it supports and strengthens it. Content flagged by AI is forwarded
          to the moderation team, and final decisions are made by human moderators. AI reduces the workload of moderators,
          enabling a faster and more consistent moderation process.
        </p>

        <h2 className="text-lg font-bold text-text-primary mt-8 mb-4">Privacy and Data Security</h2>
        <p>
          Content and data analyzed by Feedim AI are used solely for platform moderation and security purposes.
          Data obtained through AI processes is not shared with third parties, sold, or used for advertising purposes.
          All AI analyses are performed within Feedim&apos;s infrastructure.
        </p>

        <div className="bg-bg-secondary rounded-[15px] p-5 mt-8">
          <p className="text-xs text-text-muted">
            For questions about Feedim AI,{" "}
            <Link href="/help/contact" className="text-accent-main hover:opacity-80 font-semibold">Contact</Link> us
            or reach out at <a href="mailto:support@feedim.com" className="text-accent-main hover:opacity-80 font-semibold">support@feedim.com</a>.
          </p>
        </div>
      </div>
    </>
  );
}
