export const COUNTRIES = [
  { code: "AF", name_tr: "Afganistan", name_en: "Afghanistan", name_az: "Əfqanıstan" },
  { code: "AL", name_tr: "Arnavutluk", name_en: "Albania", name_az: "Albaniya" },
  { code: "DZ", name_tr: "Cezayir", name_en: "Algeria", name_az: "Əlcəzair" },
  { code: "AD", name_tr: "Andorra", name_en: "Andorra", name_az: "Andorra" },
  { code: "AO", name_tr: "Angola", name_en: "Angola", name_az: "Anqola" },
  { code: "AG", name_tr: "Antigua ve Barbuda", name_en: "Antigua and Barbuda", name_az: "Antiqua və Barbuda" },
  { code: "AR", name_tr: "Arjantin", name_en: "Argentina", name_az: "Argentina" },
  { code: "AM", name_tr: "Ermenistan", name_en: "Armenia", name_az: "Ermənistan" },
  { code: "AU", name_tr: "Avustralya", name_en: "Australia", name_az: "Avstraliya" },
  { code: "AT", name_tr: "Avusturya", name_en: "Austria", name_az: "Avstriya" },
  { code: "AZ", name_tr: "Azerbaycan", name_en: "Azerbaijan", name_az: "Azərbaycan" },
  { code: "BS", name_tr: "Bahamalar", name_en: "Bahamas", name_az: "Baham adaları" },
  { code: "BH", name_tr: "Bahreyn", name_en: "Bahrain", name_az: "Bəhreyn" },
  { code: "BD", name_tr: "Bangladeş", name_en: "Bangladesh", name_az: "Banqladeş" },
  { code: "BB", name_tr: "Barbados", name_en: "Barbados", name_az: "Barbados" },
  { code: "BY", name_tr: "Belarus", name_en: "Belarus", name_az: "Belarus" },
  { code: "BE", name_tr: "Belçika", name_en: "Belgium", name_az: "Belçika" },
  { code: "BZ", name_tr: "Belize", name_en: "Belize", name_az: "Beliz" },
  { code: "BJ", name_tr: "Benin", name_en: "Benin", name_az: "Benin" },
  { code: "BT", name_tr: "Butan", name_en: "Bhutan", name_az: "Butan" },
  { code: "BO", name_tr: "Bolivya", name_en: "Bolivia", name_az: "Boliviya" },
  { code: "BA", name_tr: "Bosna Hersek", name_en: "Bosnia and Herzegovina", name_az: "Bosniya və Herseqovina" },
  { code: "BW", name_tr: "Botsvana", name_en: "Botswana", name_az: "Botsvana" },
  { code: "BR", name_tr: "Brezilya", name_en: "Brazil", name_az: "Braziliya" },
  { code: "BN", name_tr: "Brunei", name_en: "Brunei", name_az: "Bruney" },
  { code: "BG", name_tr: "Bulgaristan", name_en: "Bulgaria", name_az: "Bolqarıstan" },
  { code: "BF", name_tr: "Burkina Faso", name_en: "Burkina Faso", name_az: "Burkina Faso" },
  { code: "BI", name_tr: "Burundi", name_en: "Burundi", name_az: "Burundi" },
  { code: "CV", name_tr: "Cabo Verde", name_en: "Cabo Verde", name_az: "Kabo Verde" },
  { code: "KH", name_tr: "Kamboçya", name_en: "Cambodia", name_az: "Kamboca" },
  { code: "CM", name_tr: "Kamerun", name_en: "Cameroon", name_az: "Kamerun" },
  { code: "CA", name_tr: "Kanada", name_en: "Canada", name_az: "Kanada" },
  { code: "CF", name_tr: "Orta Afrika Cumhuriyeti", name_en: "Central African Republic", name_az: "Mərkəzi Afrika Respublikası" },
  { code: "TD", name_tr: "Çad", name_en: "Chad", name_az: "Çad" },
  { code: "CL", name_tr: "Şili", name_en: "Chile", name_az: "Çili" },
  { code: "CN", name_tr: "Çin", name_en: "China", name_az: "Çin" },
  { code: "CO", name_tr: "Kolombiya", name_en: "Colombia", name_az: "Kolumbiya" },
  { code: "KM", name_tr: "Komorlar", name_en: "Comoros", name_az: "Komor adaları" },
  { code: "CG", name_tr: "Kongo Cumhuriyeti", name_en: "Congo", name_az: "Konqo" },
  { code: "CD", name_tr: "Kongo Demokratik Cumhuriyeti", name_en: "Congo (Democratic Republic)", name_az: "Konqo Demokratik Respublikası" },
  { code: "CR", name_tr: "Kosta Rika", name_en: "Costa Rica", name_az: "Kosta Rika" },
  { code: "CI", name_tr: "Fildişi Sahili", name_en: "Cote d'Ivoire", name_az: "Kot-d'İvuar" },
  { code: "HR", name_tr: "Hırvatistan", name_en: "Croatia", name_az: "Xorvatiya" },
  { code: "CU", name_tr: "Küba", name_en: "Cuba", name_az: "Kuba" },
  { code: "CY", name_tr: "Kıbrıs", name_en: "Cyprus", name_az: "Kipr" },
  { code: "CZ", name_tr: "Çekya", name_en: "Czechia", name_az: "Çexiya" },
  { code: "DK", name_tr: "Danimarka", name_en: "Denmark", name_az: "Danimarka" },
  { code: "DJ", name_tr: "Cibuti", name_en: "Djibouti", name_az: "Cibuti" },
  { code: "DM", name_tr: "Dominika", name_en: "Dominica", name_az: "Dominika" },
  { code: "DO", name_tr: "Dominik Cumhuriyeti", name_en: "Dominican Republic", name_az: "Dominikan Respublikası" },
  { code: "EC", name_tr: "Ekvador", name_en: "Ecuador", name_az: "Ekvador" },
  { code: "EG", name_tr: "Mısır", name_en: "Egypt", name_az: "Misir" },
  { code: "SV", name_tr: "El Salvador", name_en: "El Salvador", name_az: "Salvador" },
  { code: "GQ", name_tr: "Ekvator Ginesi", name_en: "Equatorial Guinea", name_az: "Ekvatorial Qvineya" },
  { code: "ER", name_tr: "Eritre", name_en: "Eritrea", name_az: "Eritreya" },
  { code: "EE", name_tr: "Estonya", name_en: "Estonia", name_az: "Estoniya" },
  { code: "SZ", name_tr: "Esvatini", name_en: "Eswatini", name_az: "Esvatini" },
  { code: "ET", name_tr: "Etiyopya", name_en: "Ethiopia", name_az: "Efiopiya" },
  { code: "FJ", name_tr: "Fiji", name_en: "Fiji", name_az: "Fici" },
  { code: "FI", name_tr: "Finlandiya", name_en: "Finland", name_az: "Finlandiya" },
  { code: "FR", name_tr: "Fransa", name_en: "France", name_az: "Fransa" },
  { code: "GA", name_tr: "Gabon", name_en: "Gabon", name_az: "Qabon" },
  { code: "GM", name_tr: "Gambiya", name_en: "Gambia", name_az: "Qambiya" },
  { code: "GE", name_tr: "Gürcistan", name_en: "Georgia", name_az: "Gürcüstan" },
  { code: "DE", name_tr: "Almanya", name_en: "Germany", name_az: "Almaniya" },
  { code: "GH", name_tr: "Gana", name_en: "Ghana", name_az: "Qana" },
  { code: "GR", name_tr: "Yunanistan", name_en: "Greece", name_az: "Yunanıstan" },
  { code: "GD", name_tr: "Grenada", name_en: "Grenada", name_az: "Qrenada" },
  { code: "GT", name_tr: "Guatemala", name_en: "Guatemala", name_az: "Qvatemala" },
  { code: "GN", name_tr: "Gine", name_en: "Guinea", name_az: "Qvineya" },
  { code: "GW", name_tr: "Gine-Bissau", name_en: "Guinea-Bissau", name_az: "Qvineya-Bisau" },
  { code: "GY", name_tr: "Guyana", name_en: "Guyana", name_az: "Qayana" },
  { code: "HT", name_tr: "Haiti", name_en: "Haiti", name_az: "Haiti" },
  { code: "HN", name_tr: "Honduras", name_en: "Honduras", name_az: "Honduras" },
  { code: "HU", name_tr: "Macaristan", name_en: "Hungary", name_az: "Macarıstan" },
  { code: "IS", name_tr: "İzlanda", name_en: "Iceland", name_az: "İslandiya" },
  { code: "IN", name_tr: "Hindistan", name_en: "India", name_az: "Hindistan" },
  { code: "ID", name_tr: "Endonezya", name_en: "Indonesia", name_az: "İndoneziya" },
  { code: "IR", name_tr: "İran", name_en: "Iran", name_az: "İran" },
  { code: "IQ", name_tr: "Irak", name_en: "Iraq", name_az: "İraq" },
  { code: "IE", name_tr: "İrlanda", name_en: "Ireland", name_az: "İrlandiya" },
  { code: "IL", name_tr: "İsrail", name_en: "Israel", name_az: "İsrail" },
  { code: "IT", name_tr: "İtalya", name_en: "Italy", name_az: "İtaliya" },
  { code: "JM", name_tr: "Jamaika", name_en: "Jamaica", name_az: "Yamayka" },
  { code: "JP", name_tr: "Japonya", name_en: "Japan", name_az: "Yaponiya" },
  { code: "JO", name_tr: "Ürdün", name_en: "Jordan", name_az: "İordaniya" },
  { code: "KZ", name_tr: "Kazakistan", name_en: "Kazakhstan", name_az: "Qazaxıstan" },
  { code: "KE", name_tr: "Kenya", name_en: "Kenya", name_az: "Keniya" },
  { code: "KI", name_tr: "Kiribati", name_en: "Kiribati", name_az: "Kiribati" },
  { code: "KP", name_tr: "Kuzey Kore", name_en: "Korea (North)", name_az: "Şimali Koreya" },
  { code: "KR", name_tr: "Güney Kore", name_en: "Korea (South)", name_az: "Cənubi Koreya" },
  { code: "KW", name_tr: "Kuveyt", name_en: "Kuwait", name_az: "Küveyt" },
  { code: "KG", name_tr: "Kırgızistan", name_en: "Kyrgyzstan", name_az: "Qırğızıstan" },
  { code: "LA", name_tr: "Laos", name_en: "Laos", name_az: "Laos" },
  { code: "LV", name_tr: "Letonya", name_en: "Latvia", name_az: "Latviya" },
  { code: "LB", name_tr: "Lübnan", name_en: "Lebanon", name_az: "Livan" },
  { code: "LS", name_tr: "Lesoto", name_en: "Lesotho", name_az: "Lesoto" },
  { code: "LR", name_tr: "Liberya", name_en: "Liberia", name_az: "Liberiya" },
  { code: "LY", name_tr: "Libya", name_en: "Libya", name_az: "Liviya" },
  { code: "LI", name_tr: "Lihtenştayn", name_en: "Liechtenstein", name_az: "Lixtenşteyn" },
  { code: "LT", name_tr: "Litvanya", name_en: "Lithuania", name_az: "Litva" },
  { code: "LU", name_tr: "Lüksemburg", name_en: "Luxembourg", name_az: "Lüksemburq" },
  { code: "MG", name_tr: "Madagaskar", name_en: "Madagascar", name_az: "Madaqaskar" },
  { code: "MW", name_tr: "Malavi", name_en: "Malawi", name_az: "Malavi" },
  { code: "MY", name_tr: "Malezya", name_en: "Malaysia", name_az: "Malayziya" },
  { code: "MV", name_tr: "Maldivler", name_en: "Maldives", name_az: "Maldiv adaları" },
  { code: "ML", name_tr: "Mali", name_en: "Mali", name_az: "Mali" },
  { code: "MT", name_tr: "Malta", name_en: "Malta", name_az: "Malta" },
  { code: "MH", name_tr: "Marshall Adaları", name_en: "Marshall Islands", name_az: "Marşall adaları" },
  { code: "MR", name_tr: "Moritanya", name_en: "Mauritania", name_az: "Mavritaniya" },
  { code: "MU", name_tr: "Mauritius", name_en: "Mauritius", name_az: "Mavriki" },
  { code: "MX", name_tr: "Meksika", name_en: "Mexico", name_az: "Meksika" },
  { code: "FM", name_tr: "Mikronezya", name_en: "Micronesia", name_az: "Mikroneziya" },
  { code: "MD", name_tr: "Moldova", name_en: "Moldova", name_az: "Moldova" },
  { code: "MC", name_tr: "Monako", name_en: "Monaco", name_az: "Monako" },
  { code: "MN", name_tr: "Moğolistan", name_en: "Mongolia", name_az: "Monqolustan" },
  { code: "ME", name_tr: "Karadağ", name_en: "Montenegro", name_az: "Monteneqro" },
  { code: "MA", name_tr: "Fas", name_en: "Morocco", name_az: "Mərakeş" },
  { code: "MZ", name_tr: "Mozambik", name_en: "Mozambique", name_az: "Mozambik" },
  { code: "MM", name_tr: "Myanmar", name_en: "Myanmar", name_az: "Myanma" },
  { code: "NA", name_tr: "Namibya", name_en: "Namibia", name_az: "Namibiya" },
  { code: "NR", name_tr: "Nauru", name_en: "Nauru", name_az: "Nauru" },
  { code: "NP", name_tr: "Nepal", name_en: "Nepal", name_az: "Nepal" },
  { code: "NL", name_tr: "Hollanda", name_en: "Netherlands", name_az: "Niderland" },
  { code: "NZ", name_tr: "Yeni Zelanda", name_en: "New Zealand", name_az: "Yeni Zelandiya" },
  { code: "NI", name_tr: "Nikaragua", name_en: "Nicaragua", name_az: "Nikaraqua" },
  { code: "NE", name_tr: "Nijer", name_en: "Niger", name_az: "Niger" },
  { code: "NG", name_tr: "Nijerya", name_en: "Nigeria", name_az: "Nigeriya" },
  { code: "MK", name_tr: "Kuzey Makedonya", name_en: "North Macedonia", name_az: "Şimali Makedoniya" },
  { code: "NO", name_tr: "Norveç", name_en: "Norway", name_az: "Norveç" },
  { code: "OM", name_tr: "Umman", name_en: "Oman", name_az: "Oman" },
  { code: "PK", name_tr: "Pakistan", name_en: "Pakistan", name_az: "Pakistan" },
  { code: "PW", name_tr: "Palau", name_en: "Palau", name_az: "Palau" },
  { code: "PS", name_tr: "Filistin", name_en: "Palestine", name_az: "Fələstin" },
  { code: "PA", name_tr: "Panama", name_en: "Panama", name_az: "Panama" },
  { code: "PG", name_tr: "Papua Yeni Gine", name_en: "Papua New Guinea", name_az: "Papua Yeni Qvineya" },
  { code: "PY", name_tr: "Paraguay", name_en: "Paraguay", name_az: "Paraqvay" },
  { code: "PE", name_tr: "Peru", name_en: "Peru", name_az: "Peru" },
  { code: "PH", name_tr: "Filipinler", name_en: "Philippines", name_az: "Filippin" },
  { code: "PL", name_tr: "Polonya", name_en: "Poland", name_az: "Polşa" },
  { code: "PT", name_tr: "Portekiz", name_en: "Portugal", name_az: "Portuqaliya" },
  { code: "QA", name_tr: "Katar", name_en: "Qatar", name_az: "Qətər" },
  { code: "RO", name_tr: "Romanya", name_en: "Romania", name_az: "Rumıniya" },
  { code: "RU", name_tr: "Rusya", name_en: "Russia", name_az: "Rusiya" },
  { code: "RW", name_tr: "Ruanda", name_en: "Rwanda", name_az: "Ruanda" },
  { code: "KN", name_tr: "Saint Kitts ve Nevis", name_en: "Saint Kitts and Nevis", name_az: "Sent-Kits və Nevis" },
  { code: "LC", name_tr: "Saint Lucia", name_en: "Saint Lucia", name_az: "Sent-Lüsiya" },
  { code: "VC", name_tr: "Saint Vincent ve Grenadinler", name_en: "Saint Vincent and the Grenadines", name_az: "Sent-Vinsent və Qrenadinlər" },
  { code: "WS", name_tr: "Samoa", name_en: "Samoa", name_az: "Samoa" },
  { code: "SM", name_tr: "San Marino", name_en: "San Marino", name_az: "San-Marino" },
  { code: "ST", name_tr: "Sao Tome ve Principe", name_en: "Sao Tome and Principe", name_az: "San-Tome və Prinsipi" },
  { code: "SA", name_tr: "Suudi Arabistan", name_en: "Saudi Arabia", name_az: "Səudiyyə Ərəbistanı" },
  { code: "SN", name_tr: "Senegal", name_en: "Senegal", name_az: "Seneqal" },
  { code: "RS", name_tr: "Sırbistan", name_en: "Serbia", name_az: "Serbiya" },
  { code: "SC", name_tr: "Seyşeller", name_en: "Seychelles", name_az: "Seyşel adaları" },
  { code: "SL", name_tr: "Sierra Leone", name_en: "Sierra Leone", name_az: "Syerra Leone" },
  { code: "SG", name_tr: "Singapur", name_en: "Singapore", name_az: "Sinqapur" },
  { code: "SK", name_tr: "Slovakya", name_en: "Slovakia", name_az: "Slovakiya" },
  { code: "SI", name_tr: "Slovenya", name_en: "Slovenia", name_az: "Sloveniya" },
  { code: "SB", name_tr: "Solomon Adaları", name_en: "Solomon Islands", name_az: "Solomon adaları" },
  { code: "SO", name_tr: "Somali", name_en: "Somalia", name_az: "Somali" },
  { code: "ZA", name_tr: "Güney Afrika", name_en: "South Africa", name_az: "Cənubi Afrika" },
  { code: "SS", name_tr: "Güney Sudan", name_en: "South Sudan", name_az: "Cənubi Sudan" },
  { code: "ES", name_tr: "İspanya", name_en: "Spain", name_az: "İspaniya" },
  { code: "LK", name_tr: "Sri Lanka", name_en: "Sri Lanka", name_az: "Şri-Lanka" },
  { code: "SD", name_tr: "Sudan", name_en: "Sudan", name_az: "Sudan" },
  { code: "SR", name_tr: "Surinam", name_en: "Suriname", name_az: "Surinam" },
  { code: "SE", name_tr: "İsveç", name_en: "Sweden", name_az: "İsveç" },
  { code: "CH", name_tr: "İsviçre", name_en: "Switzerland", name_az: "İsveçrə" },
  { code: "SY", name_tr: "Suriye", name_en: "Syria", name_az: "Suriya" },
  { code: "TW", name_tr: "Tayvan", name_en: "Taiwan", name_az: "Tayvan" },
  { code: "TJ", name_tr: "Tacikistan", name_en: "Tajikistan", name_az: "Tacikistan" },
  { code: "TZ", name_tr: "Tanzanya", name_en: "Tanzania", name_az: "Tanzaniya" },
  { code: "TH", name_tr: "Tayland", name_en: "Thailand", name_az: "Tayland" },
  { code: "TL", name_tr: "Doğu Timor", name_en: "Timor-Leste", name_az: "Şərqi Timor" },
  { code: "TG", name_tr: "Togo", name_en: "Togo", name_az: "Toqo" },
  { code: "TO", name_tr: "Tonga", name_en: "Tonga", name_az: "Tonqa" },
  { code: "TT", name_tr: "Trinidad ve Tobago", name_en: "Trinidad and Tobago", name_az: "Trinidad və Tobaqo" },
  { code: "TN", name_tr: "Tunus", name_en: "Tunisia", name_az: "Tunis" },
  { code: "TR", name_tr: "Türkiye", name_en: "Turkey", name_az: "Türkiyə" },
  { code: "TM", name_tr: "Türkmenistan", name_en: "Turkmenistan", name_az: "Türkmənistan" },
  { code: "TV", name_tr: "Tuvalu", name_en: "Tuvalu", name_az: "Tuvalu" },
  { code: "UG", name_tr: "Uganda", name_en: "Uganda", name_az: "Uqanda" },
  { code: "UA", name_tr: "Ukrayna", name_en: "Ukraine", name_az: "Ukrayna" },
  { code: "AE", name_tr: "Birleşik Arap Emirlikleri", name_en: "United Arab Emirates", name_az: "Birləşmiş Ərəb Əmirlikləri" },
  { code: "GB", name_tr: "Birleşik Krallık", name_en: "United Kingdom", name_az: "Birləşmiş Krallıq" },
  { code: "US", name_tr: "Amerika Birleşik Devletleri", name_en: "United States", name_az: "Amerika Birləşmiş Ştatları" },
  { code: "UY", name_tr: "Uruguay", name_en: "Uruguay", name_az: "Uruqvay" },
  { code: "UZ", name_tr: "Özbekistan", name_en: "Uzbekistan", name_az: "Özbəkistan" },
  { code: "VU", name_tr: "Vanuatu", name_en: "Vanuatu", name_az: "Vanuatu" },
  { code: "VA", name_tr: "Vatikan", name_en: "Vatican City", name_az: "Vatikan" },
  { code: "VE", name_tr: "Venezuela", name_en: "Venezuela", name_az: "Venesuela" },
  { code: "VN", name_tr: "Vietnam", name_en: "Vietnam", name_az: "Vyetnam" },
  { code: "YE", name_tr: "Yemen", name_en: "Yemen", name_az: "Yəmən" },
  { code: "ZM", name_tr: "Zambiya", name_en: "Zambia", name_az: "Zambiya" },
  { code: "ZW", name_tr: "Zimbabve", name_en: "Zimbabwe", name_az: "Zimbabve" },
  { code: "AS", name_tr: "Amerikan Samoası", name_en: "American Samoa", name_az: "Amerika Samoası" },
  { code: "AI", name_tr: "Anguilla", name_en: "Anguilla", name_az: "Angilya" },
  { code: "AW", name_tr: "Aruba", name_en: "Aruba", name_az: "Aruba" },
  { code: "BM", name_tr: "Bermuda", name_en: "Bermuda", name_az: "Bermud adaları" },
  { code: "BQ", name_tr: "Karayip Hollandası", name_en: "Bonaire, Sint Eustatius and Saba", name_az: "Karib Niderlandı" },
  { code: "VG", name_tr: "Britanya Virjin Adaları", name_en: "British Virgin Islands", name_az: "Britaniya Virgin adaları" },
  { code: "KY", name_tr: "Cayman Adaları", name_en: "Cayman Islands", name_az: "Kayman adaları" },
  { code: "CK", name_tr: "Cook Adaları", name_en: "Cook Islands", name_az: "Kuk adaları" },
  { code: "CW", name_tr: "Curaçao", name_en: "Curacao", name_az: "Kürasao" },
  { code: "FK", name_tr: "Falkland Adaları", name_en: "Falkland Islands", name_az: "Folklend adaları" },
  { code: "FO", name_tr: "Faroe Adaları", name_en: "Faroe Islands", name_az: "Farer adaları" },
  { code: "GF", name_tr: "Fransız Guyanası", name_en: "French Guiana", name_az: "Fransız Qvianası" },
  { code: "PF", name_tr: "Fransız Polinezyası", name_en: "French Polynesia", name_az: "Fransız Polineziyası" },
  { code: "GI", name_tr: "Cebelitarık", name_en: "Gibraltar", name_az: "Cəbəllütariq" },
  { code: "GL", name_tr: "Grönland", name_en: "Greenland", name_az: "Qrenlandiya" },
  { code: "GP", name_tr: "Guadeloupe", name_en: "Guadeloupe", name_az: "Qvadelupa" },
  { code: "GU", name_tr: "Guam", name_en: "Guam", name_az: "Quam" },
  { code: "GG", name_tr: "Guernsey", name_en: "Guernsey", name_az: "Gernsi" },
  { code: "HK", name_tr: "Hong Kong", name_en: "Hong Kong", name_az: "Honq Konq" },
  { code: "IM", name_tr: "Man Adası", name_en: "Isle of Man", name_az: "Men adası" },
  { code: "JE", name_tr: "Jersey", name_en: "Jersey", name_az: "Cersi" },
  { code: "XK", name_tr: "Kosova", name_en: "Kosovo", name_az: "Kosovo" },
  { code: "MO", name_tr: "Makao", name_en: "Macao", name_az: "Makao" },
  { code: "MQ", name_tr: "Martinik", name_en: "Martinique", name_az: "Martinika" },
  { code: "YT", name_tr: "Mayotte", name_en: "Mayotte", name_az: "Mayot" },
  { code: "MS", name_tr: "Montserrat", name_en: "Montserrat", name_az: "Montserrat" },
  { code: "NC", name_tr: "Yeni Kaledonya", name_en: "New Caledonia", name_az: "Yeni Kaledoniya" },
  { code: "NU", name_tr: "Niue", name_en: "Niue", name_az: "Niue" },
  { code: "NF", name_tr: "Norfolk Adası", name_en: "Norfolk Island", name_az: "Norfolk adası" },
  { code: "MP", name_tr: "Kuzey Mariana Adaları", name_en: "Northern Mariana Islands", name_az: "Şimali Marian adaları" },
  { code: "PN", name_tr: "Pitcairn Adaları", name_en: "Pitcairn Islands", name_az: "Pitkern adaları" },
  { code: "PR", name_tr: "Porto Riko", name_en: "Puerto Rico", name_az: "Puerto Riko" },
  { code: "RE", name_tr: "Reunion", name_en: "Reunion", name_az: "Reyunyon" },
  { code: "BL", name_tr: "Saint Barthelemy", name_en: "Saint Barthelemy", name_az: "Sent-Bartelemi" },
  { code: "SH", name_tr: "Saint Helena", name_en: "Saint Helena", name_az: "Müqəddəs Yelena adası" },
  { code: "MF", name_tr: "Saint Martin", name_en: "Saint Martin", name_az: "Sent-Martin" },
  { code: "PM", name_tr: "Saint Pierre ve Miquelon", name_en: "Saint Pierre and Miquelon", name_az: "Sen-Pyer və Mikelon" },
  { code: "SX", name_tr: "Sint Maarten", name_en: "Sint Maarten", name_az: "Sint-Marten" },
  { code: "TC", name_tr: "Turks ve Caicos Adaları", name_en: "Turks and Caicos Islands", name_az: "Törks və Kaykos adaları" },
  { code: "VI", name_tr: "ABD Virjin Adaları", name_en: "U.S. Virgin Islands", name_az: "ABŞ Virgin adaları" },
  { code: "WF", name_tr: "Wallis ve Futuna", name_en: "Wallis and Futuna", name_az: "Uollis və Futuna" },
  { code: "EH", name_tr: "Batı Sahra", name_en: "Western Sahara", name_az: "Qərbi Saxara" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["code"];

/**
 * Get a country by its ISO 3166-1 alpha-2 code
 */
export function getCountryByCode(code: string) {
  return COUNTRIES.find((c) => c.code === code);
}

/**
 * Get the localized name of a country
 */
export function getCountryName(
  code: string,
  locale: "tr" | "en" | "az" = "en"
): string | undefined {
  const country = getCountryByCode(code);
  if (!country) return undefined;
  const key = `name_${locale}` as const;
  return country[key];
}
