/**
 * Disposable / temporary email domain blocklist.
 * Only popular, reputable email providers are allowed.
 * Company/university/custom domains pass through (not in blocklist).
 */

const DISPOSABLE_DOMAINS = new Set([
  // 10-minute / temporary mail services
  "10minutemail.com", "10minute.email", "10minmail.com", "10mail.org",
  "tempmail.com", "temp-mail.org", "tempmail.net", "tempmail.de",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com", "grr.la", "guerrillamail.de",
  "mailinator.com", "mailinator.net", "mailinator2.com",
  "throwaway.email", "throwaway.me",
  "yopmail.com", "yopmail.fr", "yopmail.net",
  "sharklasers.com", "guerrillamail.info", "spam4.me", "grr.la",
  "dispostable.com",
  "maildrop.cc",
  "mailnesia.com",
  "tempail.com",
  "tempr.email",
  "discard.email",
  "trashmail.com", "trashmail.net", "trashmail.me", "trashmail.org",
  "trashymail.com", "trashymail.net",
  "fakeinbox.com",
  "mailcatch.com",
  "mintemail.com",
  "getnada.com", "nada.email",
  "emailondeck.com",
  "mohmal.com",
  "harakirimail.com",
  "mailnull.com",
  "spamgourmet.com",
  "mytemp.email",
  "temp.email",
  "tempinbox.com",
  "burnermail.io",
  "inboxkitten.com",
  "33mail.com",
  "mailexpire.com",
  "mailforspam.com",
  "safetymail.info",
  "filzmail.com",
  "mailsac.com",
  "mailtemp.net",
  "jetable.org",
  "crazymailing.com",
  "tempsky.com",
  "incognitomail.org",
  "trash-me.com",
  "spamfree24.org",
  "getairmail.com",
  "instant-mail.de",
  "tempomail.fr",
  "emailfake.com",
  "emltmp.com",
  "easytrashmail.com",
  "flitmail.com",
  "mailhazard.com",
  "mailmoat.com",
  "tmail.ws",
  "tmpmail.net", "tmpmail.org",
  "tempmailaddress.com",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "devnullmail.com",
  "disbox.net", "disbox.org",
  "disposeamail.com",
  "e4ward.com",
  "emailigo.de",
  "emailisvalid.com",
  "emailthe.net",
  "emailwarden.com",
  "enterto.com",
  "ephemail.net",
  "etranquil.com", "etranquil.net", "etranquil.org",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "eyepaste.com",
  "fastacura.com",
  "filzmail.com",
  "fixmail.tk",
  "flyspam.com",
  "get-mail.cf", "get-mail.ga", "get-mail.ml", "get-mail.tk",
  "getonemail.com", "getonemail.net",
  "ghosttexter.de",
  "girlsundertheinfluence.com",
  "gishpuppy.com",
  "guerrillamail.biz",
  "haltospam.com",
  "hotpop.com",
  "imstations.com",
  "inboxalias.com",
  "incognitomail.com", "incognitomail.net",
  "insorg-mail.info",
  "ipoo.org",
  "irish2me.com",
  "jetable.com", "jetable.fr.nf", "jetable.net",
  "jnxjn.com",
  "kasmail.com",
  "kaspop.com",
  "keepmymail.com",
  "klzlk.com",
  "kurzepost.de",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lol.ovpn.to",
  "lookugly.com",
  "lopl.co.cc",
  "lortemail.dk",
  "lr78.com",
  "maileater.com",
  "mailexpire.com",
  "mailfree.ga", "mailfree.gq", "mailfree.ml",
  "mailimate.com",
  "mailincubator.com",
  "mailme.ir", "mailme.lv",
  "mailmetrash.com",
  "mailnator.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailzilla.com", "mailzilla.org",
  "meltmail.com",
  "mezimages.net",
  "mierdamail.com",
  "ministry-of-silly-walks.de",
  "mt2015.com",
  "mytrashmail.com",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.xl.cx",
  "nomail2me.com",
  "nospam.ze.tc",
  "nospamfor.us",
  "nowmymail.com",
  "objectmail.com",
  "obobbo.com",
  "onewaymail.com",
  "oopi.org",
  "ordinaryamerican.net",
  "owlpic.com",
  "pjjkp.com",
  "plexolan.de",
  "pookmail.com",
  "proxymail.eu",
  "punkass.com",
  "putthisinyouremail.com",
  "qq.com",
  "quickinbox.com",
  "rcpt.at",
  "receiveee.com",
  "regbypass.com",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "scatmail.com",
  "schafmail.de",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "shiftmail.com",
  "shitmail.me", "shitmail.org",
  "shortmail.net",
  "sibmail.com",
  "skeefmail.com",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "smashmail.de",
  "soodonims.com",
  "spam.la", "spam.su",
  "spamavert.com",
  "spambob.com", "spambob.net", "spambob.org",
  "spambog.com", "spambog.de", "spambog.ru",
  "spambox.us",
  "spamcannon.com", "spamcannon.net",
  "spamcero.com",
  "spamcorptastic.com",
  "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf", "spamfighter.ga", "spamfighter.gq", "spamfighter.ml", "spamfighter.tk",
  "spamfree.eu",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com", "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrail.com",
  "spamtrap.ro",
  "speed.1s.fr",
  "superrito.com",
  "suremail.info",
  "svk.jp",
  "teleworm.us",
  "tempail.com",
  "tempalias.com",
  "tempe4mail.com",
  "tempemail.co.za", "tempemail.com", "tempemail.net",
  "tempmaildemo.com",
  "tempmailer.com", "tempmailer.de",
  "tempomail.fr",
  "thankdog.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throam.com",
  "tittbit.in",
  "tradermail.info",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "upliftnow.com",
  "uplipht.com",
  "venompen.com",
  "veryreallycheap.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org",
  "whyspam.me",
  "willhackforfood.biz",
  "wuzup.net", "wuzupmail.net",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xoxy.net",
  "yapped.net",
  "yep.it",
  "yogamaven.com",
  "yuurok.com",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",

  // More recent disposable services
  "guerrillamail.com", "mailnesia.com", "maildrop.cc",
  "mytemp.email", "tempail.com", "tempr.email",
  "inboxbear.com", "mailhub.pw", "tempemails.io",
  "1secmail.com", "1secmail.net", "1secmail.org",
  "internxt.com",
  "protonmail.ch", // ch variant sometimes used for disposable
  "cock.li", "airmail.cc", "420blaze.it",
  "tuta.io",
]);

/**
 * Check if an email domain is a known disposable/temporary service.
 * Returns true if the domain is BLOCKED (disposable).
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return true; // No domain = invalid
  return DISPOSABLE_DOMAINS.has(domain);
}
